### ISSUE TITLE
If deployed in a cluster，This Project how to support？

### ISSUE THREAD

**Issue by TUCJVXCB** [assimbly/runtime#125]
If deployed runtime project in a cluster，then i start a flow from frond-end, how can i let all node of cluster run this flow？

**Comment by skin27** [comment]
Hi @TUCJVXCB, thanks for your interest. I kind of missed this ticket (most open issues on the gateway/front-end).

Currently cluster support is limited. What currently only is possible is to share configuration and then have multiple front-ends (https://github.com/assimbly/gateway/wiki/deployment).

There is a microservice version planned so that clustering on the backend (flow-level / camel-level) will become possible.
