### ISSUE TITLE
Property body type always byte[]

### ISSUE THREAD

**Issue by Hooghof** [assimbly/runtime#285]
The property body type, which is visible in the exchanges in the transactions, has always the value 'byte[]'

Visible in all flows, but also reproduced in the test case:
Instance: development
Tenant: Regressions Tests
Group: Issues
Flow: XmlToExcel

![Image](https://github.com/user-attachments/assets/bf5b3ed5-f8ad-4422-b7b9-d06bdd5ade63)

**Comment by skin27** [comment]
Findings:

The type was derived from a variable that contains the body as byte[]. That's why it was always the same type in the properties. I checked what options are there to get the type of the object directly. There are four options:

- getName(): Full class name with package, includes array details.
- getTypeName(): Similar to getName() but useful for arrays and generics.
- getCanonicalName(): Full class name, null for local or anonymous classes.
- getSimpleName(): Only the class name without the package.

I tested with both String body and byte[] body and had the following output:

Bodytype 1: getName()    		-->  java.lang.String
Bodytype 2: getTypeName()		-->  java.lang.String
Bodytype 3: getCanonicalName()  -->  java.lang.String
Bodytype 4: getSimpleName()     -->  String
Bodytype 1: getName()			-->  [B
Bodytype 2: getTypeName()       -->  byte[]
Bodytype 3: getCanonicalName()  -->  byte[]
Bodytype 4: getSimpleName()     -->  byte[]

**Comment by skin27** [comment]
Based on the findings, I decided to got with option 4: getSimpleName()

The fix is merged into develop

**Comment by Hooghof** [comment]
Norman: What is the best way to test the body type property? Is that tied to a component or is a message validated on it?

Raymond: It's not tied to the component, it's tied to the body. It looks at what type the Java object is. For example, it is best to send text (xml, text), then it would be String (in most cases). If you send an image then it would be byte[]. etc.

Norman: You would indeed expect that, but I also come across RemoteFile, while the body is xml. What is that? (edited) 
What other types are there? By the way, I also see byte[] i.c.w. an xml body

Raymond: ‘What other types are there?’
This is unlimited. Every Java class is its own type. In Assimbly alone, we have thousands of them. In practice, you see that body is usually (and preferably) of type Spring. But sometimes it can also be Document (e.g. in XML) or List etc. It is with namely interesting to know that it is not a String, because if it is other type then most components cannot handle it.

Norman: So I can't actually do much testing on it. After a throttle, a RemoteFile body type (xml body) changes to a byte[]. I'm not sure what to do with this. (edited) 

Raymond: No, it's mostly of info. Normally, as a Java programmer, you are responsible for the type yourself. Camel has all kinds of automatic type converters built in. Only because the number of type is unlimited there are not type converters for everything, in which case it gives good information why something doesn't work.
For example, you might have a byte[] that is automatically converted to a String. With an XML or a piece of text that will work fine, but if the byte[] is the image then it goes wrong.

Raymond: There are two schools of thought in integration:
Everything is text
Everything is an object
I am of the school of leaving everything text. Text is technology-neutral. XML and JSON are just formats with structured text. Sonic tried this on the platform too.
The other school is that you should instead use the power of Java objects. For example, if you have a List object then you can allow all kinds of actions on it. Since Camel is aimed at Java programmers, they are focused on the second school. However, so if you start using it as a Low-code platform for non-Java programmers, it is sometimes unclear what happens.
Showing the Java type at least gives information on why this is so. I think experienced integration specialists can interpret this despite knowing nothing about Java.

Norman: OK clear, then I'll just leave it at that and suggest experience. It might still be worth considering changing the name of the property to JavaBodyType. That's a bit more specific I think.

**Comment by skin27** [comment]
Yes, JavaBodyType would maybe more precise, however Camel also just use BodyType, so the naming is aligned with Camel.
